{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\npycode_demo\\test_alluredemo01.py:11: AssertionError"}, "description": "this test fails", "start": 1626185680503, "stop": 1626185680503, "uuid": "079e8bab-ff77-4ea5-af8b-a1815325e0f8", "historyId": "235413fc7b29704a2ab5798bb5286b79", "testCaseId": "4d599ea8404ef6b40c61c482de44d4c5", "fullName": "pycode_demo.test_alluredemo01#test_failure", "labels": [{"name": "parentSuite", "value": "pycode_demo"}, {"name": "suite", "value": "test_alluredemo01"}, {"name": "host", "value": "LAPTOP-K8PRO4TP"}, {"name": "thread", "value": "17088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pycode_demo.test_alluredemo01"}]}